import fs from "node:fs";
import path from "node:path";
import mst from "@mstblockchain/mst-sdk";
import { ROOT_DIR, config } from "../src/config";

/**
 * Generates the keys CivicProof needs, using the MST SDK's wallet generator.
 *   npm run keys            print a .env block
 *   npm run keys -- --write append any MISSING keys to .env (never overwrites)
 *
 * Only ADMIN (and RELAYER, if different) need testnet MSTC from the faucet.
 * Guardian and device keys only sign; they never hold funds.
 */
const { Client } = mst;
const ENV_FILE = process.env.CIVICPROOF_ENV || path.join(ROOT_DIR, ".env");

const wanted = [
  ["ADMIN_PRIVATE_KEY", "deploys + configures the contract, funds the ward, emergency stop. FUND IT from the faucet."],
  ["GUARDIAN_PRIVATE_KEY", "signs GuardianApproval after rules + AI pass. Never funded."],
  ["BIN_DEVICE_PRIVATE_KEY", "bin ESP32 identity. Flash it onto the ESP32 in DEVICE_SIGNING=device mode."],
  ["COLLECTOR_DEVICE_PRIVATE_KEY", "collector ESP32 identity."],
  ["ROGUE_COLLECTOR_DEVICE_PRIVATE_KEY", "simulated dishonest contractor used by the attack scenarios."],
] as const;

const existing = fs.existsSync(ENV_FILE) ? fs.readFileSync(ENV_FILE, "utf8") : "";
const has = (k: string) => new RegExp(`^${k}=\\S+`, "m").test(existing);

const lines: string[] = [];
console.log("\nCivicProof keys (generated with @mstblockchain/mst-sdk Client.createRandom)\n");
for (const [name, why] of wanted) {
  if (has(name)) {
    console.log(`  ${name.padEnd(30)} already set in .env, skipping`);
    continue;
  }
  const client = Client.createRandom(config.rpcUrl);
  const pk = client.signer!.getPrivateKey();
  console.log(`  ${name.padEnd(30)} address ${client.signer!.address}\n  ${"".padEnd(30)} ${why}`);
  lines.push(`${name}=${pk}`);
}

if (!lines.length) {
  console.log("\nNothing to generate.\n");
} else if (process.argv.includes("--write")) {
  fs.appendFileSync(ENV_FILE, `\n# generated by npm run keys (${new Date().toISOString()})\n${lines.join("\n")}\n`);
  console.log(`\nAppended ${lines.length} key(s) to ${ENV_FILE}. Keep this file secret.\n`);
} else {
  console.log("\nAdd these to .env (or re-run with -- --write):\n");
  console.log(lines.join("\n") + "\n");
}
