import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import mst from "@mstblockchain/mst-sdk";
import { ethers } from "ethers";
import { ROOT_DIR, config } from "../src/config";

/**
 * Generates every secret the platform needs, using the MST SDK wallet
 * generator for the signing keys.
 *   npm run keys             print them
 *   npm run keys -- --write  append the missing ones to .env (never overwrites)
 * Only ADMIN needs testnet MSTC from https://faucet.masterstroke.academy;
 * setup forwards gas to the gateway and officer wallets.
 */
const { Client } = mst;
const envFile = process.env.ASTRA_ENV || path.join(ROOT_DIR, ".env");
const existing = fs.existsSync(envFile) ? fs.readFileSync(envFile, "utf8") : "";
const has = (k: string) => new RegExp(`^${k}=\\S+`, "m").test(existing);

const lines: string[] = [];
const add = (k: string, v: string, note: string) => {
  if (has(k)) return console.log(`  ${k.padEnd(24)} already set`);
  lines.push(`${k}=${v}`);
  console.log(`  ${k.padEnd(24)} ${note}`);
};

console.log("\nAstra Waste keys (signing keys generated with @mstblockchain/mst-sdk)\n");
for (const [k, note] of [
  ["ADMIN_PRIVATE_KEY", "deploys + registers + funds. FUND THIS ONE from the faucet"],
  ["GATEWAY_PRIVATE_KEY", "IoT gateway relayer (gas forwarded by setup)"],
  ["OFFICER_PRIVATE_KEY", "server-side municipal officer wallet (gas forwarded by setup)"],
  ["VERIFIER_PRIVATE_KEY", "AI verifier attestation key (no funds needed)"],
] as const) {
  const c = Client.createRandom(config.rpcUrl);
  add(k, c.signer!.getPrivateKey(), `${c.signer!.address}  ${note}`);
}
add("DEVICE_MNEMONIC", `"${ethers.Wallet.createRandom().mnemonic!.phrase}"`, "bin device identities (one key per bin)");
add("WORKER_MNEMONIC", `"${ethers.Wallet.createRandom().mnemonic!.phrase}"`, "worker payout wallets (override with WORKER_WALLET_OVERRIDES)");
add("DEVICE_MASTER_SECRET", crypto.randomBytes(32).toString("hex"), "derives each ESP32's HMAC secret");
add("SESSION_SECRET", crypto.randomBytes(32).toString("hex"), "signs login sessions");

if (!lines.length) console.log("\nNothing to add.\n");
else if (process.argv.includes("--write")) {
  fs.appendFileSync(envFile, `\n# generated by npm run keys (${new Date().toISOString()})\n${lines.join("\n")}\n`);
  console.log(`\nAppended ${lines.length} value(s) to ${envFile}. Keep it secret.\n`);
} else {
  console.log(`\nAdd these to ${envFile} (or re-run with -- --write):\n\n${lines.join("\n")}\n`);
}
